name: base

channels:
  - conda-forge

dependencies:
  - python=3.9
  - ipykernel=6.16.0
  - scikit-learn=1.1.1
  - jupyterlab=3.2.5
  - tensorboard=2.10.0
  - setuptools==59.5.0
  - conda-lock=0.13.2
  - pandas=1.3.5
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - pytest=6.2.5
  - rich=10.16.1
  - wandb=0.12.9
  - pre-commit=2.16.0
  - black=21.12b0
  - flake8=4.0.1
  - python-dotenv=0.19.2
  - pip=21.3.1
  - pip:
      - -r requirements.txt
